// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Jogos.Model.Models;

public partial class JogosDBContext : DbContext
{
    public JogosDBContext()
    {
    }

    public JogosDBContext(DbContextOptions<JogosDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Categoria> Categoria { get; set; }

    public virtual DbSet<Jogo> Jogos { get; set; }

    public virtual DbSet<JogosCategoria> JogosCategoria { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data source=Localhost;Initial Catalog=JogosDB;Integrated Security=True;TrustServerCertificate=true");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Categoria>(entity =>
        {
            entity.HasKey(e => e.CategoriaId).HasName("PK__Categori__F353C1C5543FB525");

            entity.Property(e => e.CategoriaId)
                .ValueGeneratedNever()
                .HasColumnName("CategoriaID");
            entity.Property(e => e.Nome).HasMaxLength(100);
        });

        modelBuilder.Entity<Jogo>(entity =>
        {
            entity.HasKey(e => e.JogoId).HasName("PK__Jogos__5919685597B9AEB3");

            entity.Property(e => e.JogoId).HasColumnName("JogoID");
            entity.Property(e => e.DataLancamento).HasColumnType("date");
            entity.Property(e => e.Nome).HasMaxLength(100);
        });

        modelBuilder.Entity<JogosCategoria>(entity =>
        {
            entity.HasKey(e => e.JogoCategoriaId).HasName("PK__JogosCat__C474B2AFC540B15F");

            entity.Property(e => e.JogoCategoriaId)
                .ValueGeneratedNever()
                .HasColumnName("JogoCategoriaID");
            entity.Property(e => e.CategoriaId).HasColumnName("CategoriaID");
            entity.Property(e => e.JogoId).HasColumnName("JogoID");

            entity.HasOne(d => d.Categoria).WithMany(p => p.JogosCategoria)
                .HasForeignKey(d => d.CategoriaId)
                .HasConstraintName("FK__JogosCate__Categ__29572725");

            entity.HasOne(d => d.Jogo).WithMany(p => p.JogosCategoria)
                .HasForeignKey(d => d.JogoId)
                .HasConstraintName("FK__JogosCate__JogoI__286302EC");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}